### ISSUE TITLE
Demo question

### ISSUE THREAD

**Issue by valerio-bozzolan** [hersle/leaflet-route-print#1]
Hi all! :)

I tried the [leaflet-route-print demo](https://hersle.github.io/leaflet-route-print/) and I've obtained this PDF with the default settings:

[route.pdf](https://github.com/hersle/leaflet-route-print/files/8068683/route.pdf)

![Screenshot_2022_02_15_123752](https://user-images.githubusercontent.com/6052909/154054807-41f10399-1cfa-4626-bfac-7ff5504e11f1.png)

Is this the correct behavior? I've tested in Mozilla Firefox 96 and in Chromium 98 with same results.

Thank you so much for this clarification! :)

**Comment by hersle** [comment]
Hello!

This looks like expected behavior to me.

The interface is not very well documented (yet).
Essentially, it is built upon a what-you-see-is-what-you-get idea, so if the map is zoomed out when you click print, the resolution will usually be so low that the print has very low quality.

In order to get nicer results, first zoom into the map manually in order to get your desired level of detail, **then** click print.
Keep an eye on the DPI field in the top left when you zoom. If it is colored red, then the resolution is too low acceptable results.
Does this produce better results?

**Comment by valerio-bozzolan** [comment]
OK thank you for this clarification!
